
import subprocess
from .varfilter import _parse_vcf
from .infervariants import vcf_header


def mergeVar(SR_vcf, MM_vcf, out_vcf):
    '''\
    Bcftools concat to merge the variants calls from bcftools and split read alignment


    Options:
        SR_vcf                      VCF generated by Split Read Alignment
        MM_vcf                      VCF generated by Alignment Read Mismatching
        out_vcf                     VCF with merged calls
    '''

    subprocess.call(['bcftools', 'concat',
                     '-a',
                     '-D',
                     '-Ov',
                     '-o', out_vcf,
                     SR_vcf,
                     MM_vcf])
